export const endpoints = (id?: string) => {
	return {
		auth: {
			signin: "/admin/staff/login",
			create: "/admin/staff/create",
			create_role: `/admin/role/create`,
			get_roles: `/admin/role/fetch`,
			get_admins: `/admin/staff/fetch`,
			get_admin: `/admin/staff/view-one/${id}`,
			update_admin: `/admin/staff/update/${id}`,
			request_reset: "/admin/staff/password/reset-request",
			approve_reset: "/admin/staff/password/approve-reset-request",
			reset: "/admin/staff/password/reset",
			delete_entity: `/auth/delete-entity`,
			update_role: `/admin/role/update-one/${id}`,
			change_password: "/auth/change-password",
		},
		calendar: {
			create: "/admin/calendar/events/new",
			all: "/admin/calendar/events/get-all",
			one: `${id}`,
			update: `${id}`,
			delete: `${id}`,
		},
		payments: {
			all: "/admin/payment/get-all",
			one: `/admin/payment/view-one/${id}`,
		},
		school: {
			create_exam: "/admin/examination/create-exam",
			create_exam_bundle: "/admin/examination/create-exam-bundle",
			create_class: "/admin/examination/create-class",
			create_subject: "/admin/examination/create-subject",
			create_chapter: `/admin/learning/chapter/create-new/${id}`,
			create_chapter_module: `/admin/learning/chapter-module/create-new/${id}`,
			create_questions: `/admin/learning/question/create-new/${id}`,
			get_exams: "/admin/examination/fetch-exams",
			get_exam_bundles: "/admin/examination/fetch-exam-bundles",
			get_exam_bundle: `/admin/examination/view-an-exam-bundle/${id}`,
			get_classes: "/admin/examination/fetch-classes",
			get_subjects: "/admin/examination/fetch-subjects",
			get_subject: `/admin/examination/view-a-subject/${id}`,
			get_chapters: "/admin/learning/chapter/fetch-all",
			get_chapter_modules: "/admin/learning/chapter-modules/fetch-all",
			get_questions: "/admin/learning/question/fetch-all",
			add_video: `/admin/learning/chunk_uploads/${id}`,
			update_exam: `${id}`,
			update_exam_bundle: `/admin/examination/update-exam-bundle/${id}`,
			update_class: `${id}`,
			update_subject: `/admin/examination/update-subject/${id}`,
			update_chapter: `admin/learning/chapter/update-one/${id}`,
			update_chapter_module: `admin/learning/chapter-module/update-one/${id}`,
			update_question: `/admin/learning/question/update/${id}`,
			delete: "/admin/learning/delete-entities",
			delete_entities: "admin/learning/delete-entities",
			update_quiz_settings: `admin/learning/chapter/update-quiz-settings/${id}`,
			update_chapter_sequence: "admin/learning/chapter/update-sequence",
			update_chapter_module_sequence: "admin/learning/chapter-module/update-sequence",
			publish_entity: "admin/examination/publish-resource",
			duplicate_resource: "/admin/examination/duplicate-a-subject",
		},
		settings: {
			get_config: "/admin/config/fetch",
			update_config: "/admin/config/update",
			update_admin_config: "/admin/config/update",
		},
		test_center: {
			create: "admin/test-mgt/create-new-test",
			all: "/admin/test-mgt/fetch-tests",
			one: `admin/test-mgt/view-a-test/${id}`,
			update: `/admin/test-mgt/update-test/${id}`,
			create_section: `/admin/test-mgt/create-new-test-section/${id}`,
			update_section: `/admin/test-mgt/update-test-section/${id}`,
			create_question: `/admin/test-mgt/question/create-new/${id}`,
			get_questions: `/admin/test-mgt/question/fetch-by-test-section/${id}`,
			update_question: `/admin/test-mgt/question/update/${id}`,
		},
		users: {
			all: "/admin/user/get-all",
			one: `/admin/user/view-one/${id}`,
			edit: `/admin/user/update-one/${id}`,
		},
		waitlist: {
			get: `/admin/waitlist/fetch`,
		},
		marketer: {
			get_referrals: "/admin/marketer/referral-report",
			get_withdrawals: "/admin/marketer/fetch-withdrawals",
			create_withdrawals: "/admin/marketer/make-withdrawal-request",
			verify_withdrawals: "/withdrawals/verify",
			get_banks: "/admin/payment/get-banks",
		},
	};
};
